mysql_data:
  container_name: %DOMAIN%_mysql_data
  image: sunfei/mysql_data
  
mysql:
  container_name: %DOMAIN%_mysql
  image: sunfei/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=%ROOT_PASSWORD%
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=%DB_PASSWORD%
    - MYSQL_DATABASE=%DOMAIN%
  volumes_from:
    - mysql_data

wordpress_data:
  container_name: %DOMAIN%_wordpress_data
  image: sunfei/wordpress_data
  
wordpress:
  container_name: %DOMAIN%_wordpress
  image: sunfei/wordpress
  links:
    - mysql:mysql
  environment:
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=%DB_PASSWORD%
    - WORDPRESS_DB_NAME=%DOMAIN%
    - VIRTUAL_HOST=%DOMAIN%,www.%DOMAIN%
  volumes_from:
    - wordpress_data
