mysql_data:
  container_name: %DOMAIN%_mysql_data
  image: sunfei/mysql_data
  
mysql:
  container_name: %DOMAIN%_mysql
  image: sunfei/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=%ROOT_PASSWORD%
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=%DB_PASSWORD%
    - MYSQL_DATABASE=%DOMAIN%
  volumes_from:
    - mysql_data

drupal7_data:
  container_name: %DOMAIN%_drupal7_data
  image: sunfei/drupal7_data
  
druapl7:
  container_name: %DOMAIN%_drupal7
  image: sunfei/drupal7
  links:
    - mysql:mysql
  environment:
    - VIRTUAL_HOST=%DOMAIN%,www.%DOMAIN%
  volumes_from:
    - wordpress_data
